import { DashboardLayout } from "@/components/DashboardLayout";
import { motion } from "framer-motion";
import { insights } from "@/lib/mock-data";
import { AlertTriangle, AlertCircle, Info, Bell } from "lucide-react";

const iconMap = {
  warning: AlertTriangle,
  danger: AlertCircle,
  info: Info,
};

const styleMap = {
  warning: "border-warning/30 bg-warning/5",
  danger: "border-destructive/30 bg-destructive/5",
  info: "border-primary/30 bg-primary/5",
};

const iconColorMap = {
  warning: "text-warning",
  danger: "text-destructive",
  info: "text-primary",
};

export default function AlertsPage() {
  return (
    <DashboardLayout>
      <div className="max-w-2xl mx-auto space-y-6">
        <div>
          <h2 className="text-2xl font-bold tracking-tight">Alerts</h2>
          <p className="text-sm text-muted-foreground">Notifications about your spending</p>
        </div>

        <div className="space-y-3">
          {insights.alerts.map((alert, i) => {
            const Icon = iconMap[alert.type];
            return (
              <motion.div
                key={alert.id}
                initial={{ opacity: 0, y: 12 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: i * 0.08 }}
                className={`flex items-start gap-3 p-4 rounded-xl border ${styleMap[alert.type]}`}
              >
                <Icon className={`h-5 w-5 mt-0.5 shrink-0 ${iconColorMap[alert.type]}`} />
                <p className="text-sm">{alert.message}</p>
              </motion.div>
            );
          })}
        </div>

        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.4 }}
          className="glass-card rounded-xl p-6 text-center"
        >
          <Bell className="h-8 w-8 text-muted-foreground mx-auto mb-2" />
          <p className="text-sm text-muted-foreground">
            Alerts are generated by analyzing your spending patterns with AI
          </p>
        </motion.div>
      </div>
    </DashboardLayout>
  );
}
